#spring.application.name=services
#spring.datasource.url=jdbc:postgresql://localhost:5432/socialize?createDatabaseIfNotExist=true
#spring.datasource.username=socializedmp
#spring.datasource.password=socializedmp123@
#
#spring.datasource.hikari.connection-timeout=20000
#spring.datasource.hikari.maximum-pool-size=5
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000  # 1 day
      refresh-token:
        expiration: 604800000  # 7 days

